# Generated by Django 4.2.4 on 2023-11-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_produto_id_produto_alter_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
