# Generated by Django 4.2.4 on 2023-11-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_produto_descricao_alter_produto_id_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images_products/'),
        ),
    ]
