# Generated by Django 4.2.4 on 2023-11-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='slug',
            new_name='nome_url',
        ),
    ]
