# Generated by Django 4.2.4 on 2023-11-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_slug_produto_nome_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='slug',
            new_name='nome_url',
        ),
    ]
