# Generated by Django 4.2.4 on 2023-11-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_produto_valor_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor_promocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
