# Generated by Django 4.2.4 on 2023-11-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_produto_valor_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='valor_promocao',
        ),
    ]
