# Generated by Django 4.2.4 on 2023-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_produto_valor_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
