# Generated by Django 4.2.4 on 2023-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_produto_descricao_alter_produto_id_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
