# Generated by Django 4.2.4 on 2023-11-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='mensagem',
            field=models.TextField(max_length=100),
        ),
    ]
