# Generated by Django 4.2.4 on 2023-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_feedbacks_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True)),
                ('porcentagem_desconto', models.IntegerField(default=0)),
            ],
        ),
    ]
