# Generated by Django 4.2.4 on 2023-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_cupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupons',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
