# Generated by Django 4.2.4 on 2023-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_enderecosentrega_customer_alter_ordem_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='customer',
        ),
        migrations.AddField(
            model_name='ordem',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
