# Generated by Django 4.2.4 on 2023-11-26 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0026_endereços_delete_enderecosentrega'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereços',
            new_name='Endereço',
        ),
    ]
