# Generated by Django 4.2.4 on 2023-11-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rename_endereços_endereço'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereço',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
