# Generated by Django 4.2.4 on 2023-11-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_endereço_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereço',
            old_name='endereco',
            new_name='logradouro',
        ),
        migrations.AddField(
            model_name='endereço',
            name='numero',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
