# Generated by Django 4.2.4 on 2023-11-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rename_endereco_endereço_logradouro_endereço_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereço',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
