# Generated by Django 4.2.4 on 2023-11-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_endereço_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereço',
        ),
    ]
