# Generated by Django 4.2.4 on 2023-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_endereço'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereço',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
