# Generated by Django 4.2.4 on 2023-11-28 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0033_endereço_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.CharField(max_length=50, null=True)),
                ('meio_pagamento', models.CharField(max_length=30, null=True)),
                ('endereço', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.endereço')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=shop.models.Ordem, to='shop.ordemitens')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
