# Generated by Django 4.2.4 on 2023-11-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ordem'),
        ),
    ]
