# Generated by Django 4.2.4 on 2023-11-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_rename_pedidos_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('preparando', 'Preparando'), ('enviado', 'Enviado'), ('aberto', 'Aberto')], default='aberto', max_length=20),
        ),
    ]
