# Generated by Django 4.2.4 on 2023-11-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
