# Generated by Django 4.2.4 on 2023-11-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_pedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereço',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
