# Generated by Django 4.2.4 on 2023-11-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_endereço_usuario_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='endereço',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
