# Generated by Django 4.2.4 on 2023-11-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_pedido_endereço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.produto'),
        ),
    ]
