# Generated by Django 4.2.4 on 2023-11-29 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_pedido_ordem_itenspedido_alter_pedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemitens',
            name='ordem',
        ),
        migrations.AlterField(
            model_name='ordemitens',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='shop.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ordemitens'),
        ),
        migrations.DeleteModel(
            name='ItensPedido',
        ),
    ]
