# Generated by Django 4.2.4 on 2023-11-29 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_ordemitens_ordem_alter_ordemitens_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ordemitens'),
        ),
    ]
