# Generated by Django 4.2.4 on 2023-11-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_ordemitens_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItensPedido',
        ),
    ]
