# Generated by Django 4.2.4 on 2023-11-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_remove_pedido_pedido_alter_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemitens',
            name='usuario',
        ),
    ]
