# Generated by Django 4.2.4 on 2023-11-29 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0051_remove_ordemitens_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=shop.models.Ordem, to='shop.ordemitens'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereço',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.endereço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
