# Generated by Django 4.2.4 on 2023-11-29 02:02

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_remove_pedido_status_pedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_teste',
            field=models.ForeignKey(blank=True, null=True, on_delete=shop.models.Ordem, to='shop.ordemitens'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
