# Generated by Django 4.2.4 on 2023-11-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_pedido_pedido_teste_alter_pedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
