# Generated by Django 4.2.4 on 2023-12-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='endereço',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
