# Generated by Django 4.2.4 on 2023-12-02 19:11

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_alter_pedido_endereço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_teste',
            field=models.OneToOneField(blank=True, null=True, on_delete=shop.models.Ordem, to='shop.ordemitens'),
        ),
    ]
