# Generated by Django 4.2.4 on 2023-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_alter_pedido_pedido_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_teste',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
