# Generated by Django 4.2.4 on 2023-12-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_remove_endereço_data_pedido_remove_endereço_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereço',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereço',
            name='usuario',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
