# Generated by Django 4.2.4 on 2023-12-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_endereço_nome_usuario_alter_endereço_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
