# Generated by Django 4.2.4 on 2023-12-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_alter_pedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
