# Generated by Django 4.2.4 on 2023-12-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_cupons_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupons',
            name='usuarios',
        ),
    ]
