# Generated by Django 4.2.4 on 2023-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadecontato',
            name='mensagem',
            field=models.TextField(max_length=300),
        ),
    ]
