# Generated by Django 4.2.4 on 2023-11-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_areadecontato_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Não realizado', max_length=30, null=True)),
            ],
            options={
                'ordering': ('status',),
            },
        ),
        migrations.AddField(
            model_name='areadecontato',
            name='contato_realizado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='website.statuscontato'),
        ),
    ]
