# Generated by Django 4.2.4 on 2023-11-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_statuscontato_areadecontato_contato_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontato',
            name='identificacao',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='areadecontato',
            name='contato_realizado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='website.statuscontato'),
        ),
        migrations.AlterField(
            model_name='statuscontato',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
