# Generated by Django 4.2.4 on 2023-11-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_statuscontato_identificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadecontato',
            name='contato_realizado',
            field=models.TextField(null=True, verbose_name='não'),
        ),
        migrations.DeleteModel(
            name='StatusContato',
        ),
    ]
