# Generated by Django 4.2.4 on 2023-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_areadecontato_contato_realizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areadecontato',
            name='contato_realizado',
        ),
        migrations.AddField(
            model_name='areadecontato',
            name='status_contato',
            field=models.TextField(null=True),
        ),
    ]
