# Generated by Django 4.2.4 on 2023-11-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_areadecontato_contato_realizado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreadeContato',
            new_name='FormularioContato',
        ),
    ]
