# Generated by Django 4.2.4 on 2023-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_areadecontato_formulariocontato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocontato',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='formulariocontato',
            name='status_contato',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
