# Generated by Django 4.2.4 on 2023-10-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_customuser_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
