# Generated by Django 4.2.4 on 2023-10-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='senha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
