# Generated by Django 4.2.4 on 2023-10-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='senha',
        ),
    ]
