# Generated by Django 4.2.4 on 2023-10-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_customuser_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
