# Generated by Django 4.2.4 on 2023-10-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_data_nascimento_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='data_nascimento',
        ),
    ]
