# Generated by Django 4.2.4 on 2023-10-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_customuser_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
