# Generated by Django 4.2.4 on 2023-10-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verificado',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
