# Generated by Django 4.2.4 on 2023-10-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_customuser_email_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
