# Generated by Django 4.2.4 on 2023-10-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customuser_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
