# Generated by Django 4.2.4 on 2023-10-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_customuser_email_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img_perfil',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
