# Generated by Django 4.2.4 on 2023-10-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_customuser_img_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='img_perfil',
        ),
    ]
