# Generated by Django 4.2.4 on 2023-11-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_customuser_img_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verificado',
        ),
    ]
