# Generated by Django 4.2.4 on 2023-11-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_endereço'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereço',
        ),
    ]
